# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Direccion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Civile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Ciudade')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Infracciones',
            fields=[
                ('ID_Infracciones', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Lugar', models.CharField(max_length=30)),
                ('Articulo', models.CharField(max_length=120)),
                ('Costo', models.IntegerField()),
                ('Persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Civile')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('ID_Marca', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Casa')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('ID_Modelo', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField()),
                ('Infracciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Infracciones')),
                ('Persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Civile')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('ID_Persona', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellido', models.CharField(max_length=30)),
                ('Direccion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('ID_vehicuo', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('Fecha_Matriculacion', models.DateTimeField()),
                ('Modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Modelo')),
                ('Persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='multa',
            name='vehicuo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Vehiculo'),
        ),
        migrations.AddField(
            model_name='civile',
            name='ID_Persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Persona'),
        ),
        migrations.AddField(
            model_name='civile',
            name='Tipo_Persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Tipo_Persona'),
        ),
        migrations.AddField(
            model_name='ciudade',
            name='Departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Departamento'),
        ),
    ]
