# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('ID_Casa', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Direccion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('ID_Ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('ID_Departamento', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Infracciones',
            fields=[
                ('ID_Infracciones', models.AutoField(primary_key=True, serialize=False)),
                ('Lugar', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('ID_Marca', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('ID_Casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Casa')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('ID_Modelo', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('ID_Marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('ID_Multa', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.CharField(max_length=8)),
                ('Articulo', models.CharField(max_length=120)),
                ('Costo', models.IntegerField()),
                ('ID_Infracciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Infracciones')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('ID_Persona', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellido', models.CharField(max_length=30)),
                ('Direccion', models.CharField(max_length=30)),
                ('ID_Ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Persona',
            fields=[
                ('ID_Tipo_Persona', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('ID_vehicuo', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('Fecha_Matriculacion', models.CharField(max_length=8)),
                ('ID_Modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Modelo')),
                ('ID_Persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='ID_Tipo_Persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Tipo_Persona'),
        ),
        migrations.AddField(
            model_name='multa',
            name='ID_Persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Persona'),
        ),
        migrations.AddField(
            model_name='multa',
            name='ID_vehicuo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Vehiculo'),
        ),
        migrations.AddField(
            model_name='infracciones',
            name='ID_Persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Persona'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='ID_Departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Departamento'),
        ),
    ]
