# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Direccion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Civile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Ciudade')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Infracciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Articulo', models.CharField(max_length=120)),
                ('Costo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('ID_Casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Casa')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('ID_Marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lugar', models.CharField(max_length=30)),
                ('Fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('ID_Agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Civile')),
                ('ID_Infracciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Infracciones')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('ID_Persona', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellido', models.CharField(max_length=30)),
                ('Direccion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('ID_vehiculo', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('Fecha_Matriculacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('ID_Modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Modelo')),
                ('ID_Persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='multa',
            name='ID_Pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Pago'),
        ),
        migrations.AddField(
            model_name='multa',
            name='ID_Persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Persona'),
        ),
        migrations.AddField(
            model_name='multa',
            name='ID_vehicuo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Vehiculo'),
        ),
        migrations.AddField(
            model_name='civile',
            name='ID_Persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Persona'),
        ),
        migrations.AddField(
            model_name='civile',
            name='ID_Tipo_Persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Tipo_Persona'),
        ),
        migrations.AddField(
            model_name='ciudade',
            name='ID_Departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Departamento'),
        ),
        migrations.AddField(
            model_name='casa',
            name='ID_Ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.Ciudade'),
        ),
    ]
