# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0002_auto_20160511_1129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ciudad',
            new_name='Ciudade',
        ),
        migrations.AlterField(
            model_name='multa',
            name='Fecha',
            field=models.DateTimeField(),
        ),
    ]
