# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0003_auto_20160511_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='Fecha_Matriculacion',
            field=models.DateTimeField(),
        ),
    ]
